### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [brett099/prj-rev-bwfs-tea-cozy#4]
Grade: Meets Expectations

Summary:
Brett, congrats on finishing the Tea Cozy project! Overall you did a great job on the project, both your files were readable considering you used descriptive id names, class names and commented both your files thoroughly. Apart from this structurally and syntactically I saw minimal issues with the only one being the missing alt attributes in your images. 

I did notice that on wide screens your content isn't always centered like your background-1. I suggest you take a look at this [HTML](https://gist.github.com/jim-rosales/46f2f87823e2546e3e1da4427e72bb48) and [CSS](https://gist.github.com/jim-rosales/f7e0153c0bb6a2c9563d415b9b4d44dc) solution to see how you can change the structure of your HTML and CSS, so it is always centered no matter the width of a users screen. 

As extra practice consider adding some [hover effects](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) along with some [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions) to your project. Both are frequently used together to add visual feedback to some user actions. For inspiration take a look at this [codepen](https://codepen.io/JacobStone/pen/GfLEn) that shows how both can be used together.

**Comment by brett099** [comment]
thank you jim i will start adding alt attributes to my image tags and im hoping the next unit will tech me more about the responsive side on web design so i can fix my issues with different screen sizes

**Comment by brett099** [comment]
teach*

**Comment by jim-rosales** [comment]
You're welcome, Brett! I'm sure the next unit will teach you more about responsive design but if you want to do some more reading on your own feel free to take a look at this [resource](https://developers.google.com/web/fundamentals/design-and-ux/responsive/). Happy Coding!
